In [4]:
import numpy as np


In [5]:
class SodokuSolver:
    '''
    inputType (Values): Nested list [ [], [], [], [], ], where the length of the nested array = length of
    outer array. This creates a square matrix

    rtype: Nested list(NxN) of the solved grid. Returns a list of the rows from top to bottom of the grid

    '''
    
    def __init__(self, values):
        self.grid = np.array(values)
    
#     def __str__(self): doesnt work as desired
#         return self.grid 
    
    def isPossible(self, x, y, n):
        '''
        In Matrix notation, insert n in position (Y x X)
        x: column number, start from 0
        y: row number, start from 0
        n: value to insert, 1-9
        '''
        for i in range(9): #Check columns 0-8 for value n in position x
            if (self.grid[i][x] == n):
                return False

        for i in range(9): #check row y for value n in positions 0-8
            if (self.grid[y][i] == n):
                return False
            
        x_loc_mini_grid = x//3
        y_loc_mini_grid = y//3
        
        for i in range(y_loc_mini_grid*3, y_loc_mini_grid*3 + 2):
            for j in range(x_loc_mini_grid*3, x_loc_mini_grid*3 + 2):
                if (self.grid[i][j] == n):
                    return False
        return True
    
    def solve(self):
        try:
            for i in range(9):
                for j in range(9):
                    if self.grid[i][j] == 0:
                        for n in range(1,10):
                            if self.isPossible(i,j,n):
                                self.grid[i][j] = n
                                self.solve()
                                self.grid[i][j] = 0
                        return
            print(self.grid)
            input('More?')
        except KeyboardInterrupt:
            print(self.grid)
        
        

In [6]:
first = SodokuSolver([[0,0,0,6,0,0,4,0,7], 
                      [0,9,6,0,0,7,0,8,5], 
                      [0,2,5,9,4,0,0,0,0],
                      [9,4,1,0,2,0,0,0,0],
                      [0,8,0,4,0,5,0,1,0],
                      [0,0,0,0,3,0,8,2,4],
                      [0,0,0,0,8,4,1,7,0],
                      [1,5,0,7,0,0,9,4,0],
                      [8,0,4,0,0,1,0,0,0]])
print(first.grid)


[[0 0 0 6 0 0 4 0 7]
 [0 9 6 0 0 7 0 8 5]
 [0 2 5 9 4 0 0 0 0]
 [9 4 1 0 2 0 0 0 0]
 [0 8 0 4 0 5 0 1 0]
 [0 0 0 0 3 0 8 2 4]
 [0 0 0 0 8 4 1 7 0]
 [1 5 0 7 0 0 9 4 0]
 [8 0 4 0 0 1 0 0 0]]


In [ ]:
first.solve()