In [0]:
import numpy as np


In [0]:
class SudokuSolver:
    '''
    inputType (Values): Nested list [ [], [], [], [], ], where the length of the nested array = length of
    outer array. This creates a square matrix

    rtype: Nested list(NxN) of the solved grid. Returns a list of the rows from top to bottom of the grid

    '''
    
    def __init__(self, values):
        self.grid = np.array(values)
    
#     def __str__(self): doesnt work as desired
#         return self.grid 
    
    def isPossible(self, y, x, n):
        '''
        In Matrix notation, insert n in position (Y x X)
        x: column number, start from 0
        y: row number, start from 0
        n: value to insert, 1-9
        '''
        for i in range(9): #Check columns 0-8 for value n in position x
            if (self.grid[i][x] == n):
                return False

        for i in range(9): #check row y for value n in positions 0-8
            if (self.grid[y][i] == n):
                return False
            
        x_loc_mini_grid = x//3
        y_loc_mini_grid = y//3
        
        for i in range(y_loc_mini_grid*3, y_loc_mini_grid*3 + 3):
            for j in range(x_loc_mini_grid*3, x_loc_mini_grid*3 + 3):
                if (self.grid[i][j] == n):
                    return False
        return True
    
    def solve(self):

          for x in range(9):
              for y in range(9):
                  if self.grid[y][x] == 0:
                      for n in range(1,10):
                          if self.isPossible(y,x,n):
                              self.grid[y][x] = n
                              self.solve()
                              self.grid[y][x] = 0
                      return
          print(self.grid)
          print()
          input('More?')
        

In [39]:
first = SudokuSolver([[0,0,0,6,0,0,4,0,7], 
                      [0,9,6,0,0,7,0,8,5], 
                      [0,2,5,9,4,0,0,0,0],
                      [9,4,1,0,2,0,0,0,0],
                      [0,8,0,4,0,5,0,1,0],
                      [0,0,0,0,3,0,8,2,4],
                      [0,0,0,0,8,4,1,7,0],
                      [1,5,0,7,0,0,9,4,0],
                      [8,0,4,0,0,1,0,0,0]])
print(first.grid)


[[0 0 0 6 0 0 4 0 7]
 [0 9 6 0 0 7 0 8 5]
 [0 2 5 9 4 0 0 0 0]
 [9 4 1 0 2 0 0 0 0]
 [0 8 0 4 0 5 0 1 0]
 [0 0 0 0 3 0 8 2 4]
 [0 0 0 0 8 4 1 7 0]
 [1 5 0 7 0 0 9 4 0]
 [8 0 4 0 0 1 0 0 0]]


In [40]:
first.solve()

[[3 1 8 6 5 2 4 9 7]
 [4 9 6 3 1 7 2 8 5]
 [7 2 5 9 4 8 3 6 1]
 [9 4 1 8 2 6 7 5 3]
 [2 8 3 4 7 5 6 1 9]
 [5 6 7 1 3 9 8 2 4]
 [6 3 9 5 8 4 1 7 2]
 [1 5 2 7 6 3 9 4 8]
 [8 7 4 2 9 1 5 3 6]]

More?


In [37]:
second = SudokuSolver([[0,9,0,7,0,0,0,4,0],
                       [7,0,0,4,0,8,0,0,9],
                       [0,1,0,6,0,0,0,0,0],
                       [0,4,0,0,0,0,5,0,8],
                       [1,0,0,0,0,0,0,0,2],
                       [8,0,6,0,0,0,0,9,0],
                       [0,0,0,0,0,4,0,5,0],
                       [9,0,0,3,0,2,0,0,1],
                       [0,3,0,0,0,1,0,7,0]])

second.solve()

[[2 9 8 7 1 3 6 4 5]
 [7 6 3 4 5 8 1 2 9]
 [5 1 4 6 2 9 8 3 7]
 [3 4 7 2 9 6 5 1 8]
 [1 5 9 8 4 7 3 6 2]
 [8 2 6 1 3 5 7 9 4]
 [6 8 1 9 7 4 2 5 3]
 [9 7 5 3 6 2 4 8 1]
 [4 3 2 5 8 1 9 7 6]]

More?


In [41]:
second = SudokuSolver([[0,9,0,7,0,0,0,4,0],
                       [7,0,0,4,0,8,0,0,9],
                       [0,1,0,6,0,0,0,0,0],
                       [0,4,0,0,0,0,5,0,8],
                       [1,0,0,0,0,0,0,0,2],
                       [8,0,6,0,0,0,0,9,0],
                       [0,0,0,0,0,4,0,5,0],
                       [9,0,0,3,0,2,0,0,1],
                       [0,3,0,0,0,1,0,7,0]])

second.solve()

[[2 9 8 7 1 3 6 4 5]
 [7 6 3 4 5 8 1 2 9]
 [5 1 4 6 2 9 8 3 7]
 [3 4 7 2 9 6 5 1 8]
 [1 5 9 8 4 7 3 6 2]
 [8 2 6 1 3 5 7 9 4]
 [6 8 1 9 7 4 2 5 3]
 [9 7 5 3 6 2 4 8 1]
 [4 3 2 5 8 1 9 7 6]]

More?
